---
title: "Blackjack"
author: "Guillaume Donnet"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

## Preliminaries
```{r}
# change working directory 
# setwd("C:/Users/gus/projet/R/blackjack")

# read the csv definition of a full deck
# also ensure we only import the first three columns
single_deck <- read.csv("deck.csv", sep=";")[, 1:3]

# first, we create a Black Jack deck by combining four full decks 
# this will actually be a global variable, used but never modified
four_decks <- rbind(single_deck, single_deck, single_deck, single_deck)
```

## Printing helpers
```{r}
# given a data.frame of hands, this function 
# cat to the console face, suite, value for each card (rows)
cat_deck <- function(x){
  for (i in 1:nrow(x)) 
    cat("\t- ", paste(x[i, ], sep=" "), "\n")
  cat("\t+  sum:", sum(x$value))
}

# This one cat a full report of hands and and chances
# it does not require arguments since we use global variables
cat_status <- function(){
  # cat a current stage message on the console
  # cat("\n", rep("*", 10), " Current state ", rep("*", 10), sep="")
  cat(" - Dealers hand:\n")
  cat_deck(dealers)
  cat("\n - Your hand:\n")
  cat_deck(yours)
  # calculate chances to win
  calculate_chances()
}


```

## Game functions
```{r}
# Given a data.frame, use sample to shuffle
shuffle_deck <- function(x) { 
  # by default, sample() simply shuffle its first argument
  # with replace=FALSE. Here, we use it on the x rows
  x[sample(1:nrow(x)), ]
}

# Initialize the game by shuffling the 'four_decks' variables, which creates the 'casino_deck'  global variable.
# Deck is shuffled once for all. Then draw two cards for the dealer, two for you
# and assign these decks to global variables. (And also remove them from the 'casino_deck'). Finally print the first status.
start_game <- function() {
  # shuffle
  casino_deck <- shuffle_deck(four_decks)
  
  # since it has been shuffled we can arbitrarily take any two sets of two cards
  # let's keep it simple, so we go for the first two for the dealer
  # create global variables on the fly.
  dealers <<- casino_deck[1:2, ]
  # and the next two for myself
  yours   <<- casino_deck[3:4, ]
  # then remove the first three and turn casino_deck_shuffled into a global
  # variable 'casino_deck_shuffled'
  casino_deck <<- casino_deck[-(1:4), ]
  
  # use cat_status to print full report on the console
  cat_status()
}

# a function that calculates chances and cat it, nicely formatted
# does not require arguments since the three of them (dealers, yours and casino_deck are global variables)
calculate_chances <- function(){
  # calculate sum in each hand
  yours_sum <- sum(yours$value)
  dealers_sum <- sum(dealers$value)
  # if more than 21, you lose
  if (yours_sum > 21){
    prob <- 0
  } else {
    # otherwise sum up remaining values, ie all remaining cards
    # add your current hand, and test whether you're still <= 21
    next_sum <- (casino_deck$value + yours_sum)
    winning_draw <- (next_sum <= 21) & (next_sum >= dealers_sum)
    # chances to win is simply the average of this logical vector
    prob <- mean(winning_draw)
  }
  # turn prob into a nicely formatted percentage
  # we have ~200 hundred cards so we can go for a 0.5% accuracy
  # but say we go for one decimal
  prob_pc <- round(100*prob)
  cat("\n - Chances:",  prob_pc, "%")
}

# this function simply remove the top card (row) of the global variable # 'casino_deck', which is already shuffled, add it to 'yours'
# then use cat_status
deal <- function(){ 
  yours <<- rbind(yours, casino_deck[1, ])
  casino_deck <<- casino_deck[-1, ]
  cat_status()
}

# Verdict of the game
# begins like calculate sum and ends up with a victory/defeat message
stop_game <- function(){
  # calculate sum in each hand
  yours_sum <- sum(yours$value)
  dealers_sum <- sum(dealers$value)
  # if more than 21, you lose
  if (yours_sum > 21){
    victory <- FALSE
  } else {
    # otherwise just compare if above or equal
    victory <- (yours_sum >= dealers_sum)
  }
  # Finally print a status
  if (victory)
    cat("\n - You win :)")
  else
    cat("\n - You lose :(")
}
```

## Examples

```{r}
# this ensure replicability of our meaningful examples
set.seed(2022)
```

### ex 1
```{r}
start_game()
stop_game() # victory: cautious but winning decision
```

### ex 2
```{r}
start_game()
stop_game() # defeat: caution does not work all the time...
```

### ex 3
```{r}
start_game()
deal()      # fingers crossed..
stop_game() # but defeat!
```

### ex 4
```{r}
start_game()
deal()      # the only possible way to win is to draw at least 2 more cards
deal()
stop_game() # but defeat! we want to end on a victory
```

### ex 5
```{r}
start_game()
stop_game() # here it is!
```